modLoader = "javafml"
loaderVersion = "[40,)"
license = "GPL3"

[[mods]]
modId = "kubeutils"
version = "${version}"
displayName = "KubeUtils"
authors="ErrorMikey"
description = '''
Provides extra methods and tools to the standard KubeJS mod
'''

[[dependencies.kubeutils]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubeutils]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubeutils]]
modId = "kubejs"
mandatory = true
# See above for how to read this notation, this essentially means any
# version of Minecraft from 1.18.2 (inclusive).
versionRange = "[1802.5.4-build.533,)"
ordering = "NONE"
side = "BOTH"
