name: Release

on:
  push:
    tags:
      - "release/1.*/*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Publish
        uses: gradle/gradle-build-action@v2
        env:
          NANITE_TOKEN: ${{ secrets.NANITE_DEPLOY }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSE_DEPLOY }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: build publish publishMods
